# Site settings
title: Phantom portfolio 
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Phantom
user_description: ë‚˜ë§Œì˜ í¬íŠ¸í´ë¦¬ì˜¤ë¥¼ ë§Œë“¤ì—ˆìŠµë‹ˆë‹¤. ê°œë°œì ê³µë¶€ë¥¼ ì‹œì‘í•œì§€ ì–¼ë§ˆë˜ì§€ì•Šì•„ ê¾¸ì¤€í•œ ê³µë¶€ë¥¼ í†µí•´ ë‚˜ì˜ ì§€ì‹ì„ ì€í•˜ğŸŒŒ ì²˜ëŸ¼ ë§Œë“¤ê³  ì„œë¡œ ì—°ê²°í•˜ì—¬ ìš°ì£¼ì²˜ëŸ¼ ë§Œë“¤ê³  ì‹¶ë‹¤ëŠ” ìƒê°ì— ë‚˜ë§Œì˜ ìš°ì£¼ë¼ê³  í‘œí˜„ì„ í–ˆìŠµë‹ˆë‹¤.
user_title: íŒ¬í…€ì˜ ìš°ì£¼ì— ì˜¤ì‹ ê²ƒì„ í™˜ì˜í•©ë‹ˆë‹¤.
email: ksj0633@naver.com
instagram_username: 7bsangjoon
github_username:  Kim-Phantom
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

